### ISSUE TITLE
Enable Support for Patterns

### ISSUE THREAD

**Issue by tirthaguha** [ai/nanoid#105]
Is it possible to generate id based on a given pattern
e.g.
`
generate('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', 5); //returns 5LSHO
`
could be extended to 
`
generate('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', 5, 'XXX-XX'); //could return 5LS-HO
`

**Comment by ai** [comment]
There are 2 problems with this feature:

1. It will increase Nano ID size.
2. It is not very popular.

As result, I can’t add it, since it will affect the main Nano ID benefit of having small size.

You may take any pattern library and use it together with Nano ID: `pattern(generate(alphabet, 5), 'XXX-XX')`. Is it OK for you?

**Comment by aidarkhanov** [comment]
Walking by, I am just interested, what if pattern feature would be a separate package?

**Comment by ai** [comment]
> Walking by, I am just interested, what if pattern feature would be a separate package?

I think it will be the best option.

**Comment by alejandroiglesias** [comment]
Then? What is the recommended implementation for patterns? I'm new to this package and I'm starting to look into code that uses it and I need to fix an issue by preventing the generated ID to start with a digit (fails for CSS classes trying to be queried by the `querySelector` API).
