### ISSUE TITLE
Probability of collision

### ISSUE THREAD

**Issue by GunterJameda** [ai/nanoid#154]
Hey, @ai!

I'm using `shortid-36`, a modification of Dylan Greene's `shortid`, in which you are (were?) a collaborator. I noticed you are telling people to use `nanoid` instead of `shortid` because it's dead. And well, let's be honest: at least `nanoid` is being improved every week or what, so we can count on you to update the project if something goes wrong.

I have one question to understand if this package meets my needs or not.

Let's suppose I have a software I want to sell to my clients. Let's say there are millions of clients all around the world. The software works mainly offline. Only sometimes it does something online. The software allows you to create projects and develop projects (like an IDE). For each project created, the software will randomly generate a short id using `nanoid`. This is completely local and requires no internet connection. The client can, later on, publish his project to the world, in which case we'll need to send a bunch of files to a server, in which they will be stored in a folder named exactly the same as that generated short id.

The project is working in a lot of computers. Is there any probability that there will be 2 projects created in 2 different computers with same id, meaning the one to publish the project later will be the one that will prevail? If not, how could I assure it would happen without sending any requests to the server?

I'm not sure I explained the question very weel. Please, feel free to ask any questions if not.

Thanks!

**Comment by ai** [comment]
> I noticed you are telling people to use nanoid instead of shortid because it's dead.

The main problem behind `shortid` is their architecture leads to collisions in some cases (because collision protection is based on current machine memory, which will not work in a distributed system). The lack of maintenance is just a result of that fundamental problem.

> Is there any probability that there will be 2 projects created in 2 different computers with same id, meaning the one to publish the project later will be the one that will prevail?

We have a special tool to calculate collision probability: [zelark.github.io/nano-id-cc/](https://zelark.github.io/nano-id-cc/]

If your clients will generate 1 project per hour, you will have 1 000 000 ID generation per hour. With default alphabet and ID length **~1 billion years needed, in order to have a 1% probability of at least one collision**.
