### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by nainardev** [ai/nanoid#172]
TypeScript has numerous advantages over JS, and allows type checking

**Comment by ai** [comment]
Build a step (with any compiler) is not an option for me after my bad experience with PostCSS maintenance.

1. I want to be able to test `master` on production by `"nanoid": "ai/nanoid"` in `package.json`.
2. For Nano ID it is very critical to control JS output. Compilers often insert a lot of unnecessary code. Removing Babel always increase to size.

Also, since Java, I am not a big fan of the current generation of typing. It requires a lot of time thinking about types and anyway does not replace a good testing system. It is OK to use them if you like. But our history shows that choosing to use types or not to use them is a mostly subjective thing, rather than a strong objective reason. We had a lot of big and cool projects without typing (remember all Ruby trend 10 years ago).
