### ISSUE TITLE
Size inconsistency

### ISSUE THREAD

**Issue by nainardev** [ai/nanoid#178]
Bundle phobia says it 269B
You say it below that. I'm confused

https://bundlephobia.com/result?p=nanoid@2.1.11

**Comment by ai** [comment]
NanoID uses different [Size Limit](https://github.com/ai/size-limit/) metric.

* Bundlephobia builds your library by webpack and shows the bundle size. It is not accurate, because it also shows webpack’s code size.
* Size Limit build empty project with webpack, then add your library and see a difference between a project with lib and empty project. In this case, we track only the size of the library without webpack runtime.

I think the difference in metrics is not so big deal when you use the same method to compare. In comparing with `uuid` I used the Size Limit metrics too.
