### ISSUE TITLE
What are some use cases for nanoid?

### ISSUE THREAD

**Issue by dylanirlbeck** [ai/nanoid#181]
Hi all. I've recently come across this library and think that the concept is incredibly cool! However, I'm struggling too see what kinds of projects or applications would have a use for `nanoid`. It's my understanding that databases have built-in UUID features, so I'm not sure in which cases someone would use this library. Any information on these use cases or links to examples of projects that use this library would be greatly appreciated.

Thanks in advance!

**Comment by ai** [comment]
1. I use Nano ID to generate a unique client ID and unique action ID in [Logux](https://logux.io).
2. Many people use Nano ID to generate model ID when you need to have ID before you will send data to the database. For instance, it is important in Offline-first and Optimistic UI.
3. Some users use it to generate unique code for URL. UUID will be too long to enter it manually.
4. Also, it can be used to generate unique password or token. It is more compact than UUID.

**Comment by ai** [comment]
In general Nano ID can be used in:

1. Distributed systems. Hardware randomness reduces collision probability.
2. Unpredicted password/token generation.

UUID can be used there as well, but UUID is longer (and also npm’s `uuid/v4` is slower and bigger than Nano ID).

**Comment by TrySound** [comment]
It's `import { v4 as uuidv4 } from 'uuid'` now

**Comment by ai** [comment]
So long import 😣 people use ESM not in the best way

**Comment by TrySound** [comment]
People use default export not in the best way. It meant to be only commonjs interop. Instead we get ton of issues because of incorrectly configured typescript.

We all could be much happier if `module.exports` and `export default` did not exist.

**Comment by dylanirlbeck** [comment]
Thank you so much!

**Comment by bipinstha7** [comment]
@ai , I think we can use nanoid to generate APP SECRET KEYS? 
I am using `crypto.pbkdf2(secret, salt, iteration, length, algorithm)` with a single iteration to generate secret keys. Am I using the right way of implementation?

And I have a question about nanoid's predictability. The collision calculator says - _**For 21 characters length and 1000 IDs per hour, ~149 billion years needed, in order to have a 1% probability of at least one collision.**_ 
Does that mean only after ~149 billion years there is a chance of collision? and before that zero probability of collision?
If the answer is yes, what is the algorithm or implementation that extends the probability ~149 billion years? I have been confused with this for a long time.

and thank you for the awesome package and your contribution to the community. :)

**Comment by ai** [comment]
You should be able to use NanoID for keys. They are unique and unpredictable.

> Does that mean only after ~149 billion years there is a chance of collision? and before that zero probability of collision?

Because NanoID used random IDs, you always have some chances for collision.

But because ID is so long, these chances is very low.
