### ISSUE TITLE
Uniformity questions/discussion

### ISSUE THREAD

**Issue by akx** [ai/nanoid#19]
The security section proclaims `random % alphabet` to be insecure, and it understandably is, when the range of `random` isn't divisible by the length of `alphabet` and parts of the random space get "folded" into the smaller space. (I'm sure there's a mathematical term for this...) Anyway, it would be nice if the readme explained why the above algorithm is bad.

So I started wondering about the usual `Math.random() * alphabet.length` approach and tested it a bit: https://gist.github.com/akx/7afb144ed2b4d32886a29bfd45e7986f

With 100,000 characters generated, the distribution seems reasonably uniform:

![image](https://user-images.githubusercontent.com/58669/30327278-254f0eb4-97d4-11e7-883a-56c71e22156a.png)

(The "dip" at the lower values disappears on subsequent runs, so it's nothing to worry about.)

However, using `const cryptoRand = () => crypto.randomBytes(1)[0] / 255.;` as the `rand` function, the distribution is significantly non-uniform, which is kind of strange. (Can someone explain what's happening there?)

![image](https://user-images.githubusercontent.com/58669/30327442-c852338e-97d4-11e7-9cb6-e5df07217466.png)

* The same profile remained over multiple trials.
* The same profile occurs on both OSX and Moby Linux, as run by Docker-on-Mac.
* Also, to rule out any weirdness that might be caused by requesting only one byte at a time, I tested with an approach that fills in a larger buffer of `randomBytes`.

(ps. What's the magic 1.6 in https://github.com/ai/nanoid/blob/c59016d31ce5cd6c8aafd89b884afadbfa8bd37c/format.js#L32 ? :D )

**Comment by ai** [comment]
> Anyway, it would be nice if the readme explained why the above algorithm is bad.

I agree. But I am not so good in English for so complex topic :sweat_smile:. As a solution, I put a link to a great article with a good explanation. If you think this link doesn’t work here?

**Comment by ai** [comment]
> Math.random() * alphabet.length

Clever way! :) I like it.

(it could not be used in `nanoid` since we use hardware random generator. And this RNG returns integers, not floats).

**Comment by ai** [comment]
> var step = Math.ceil(1.6 * mask * size / alphabet.length) 

Finally, somebody asked about all these crazy hacks :D. We have two hacks here.

We have a problem. RNG gives as numbers between `0…255` but we need smaller subset `0…n`. We can’t call `random() % n` because of distribution problems.

This is why we remove all random numbers bigger than `n`. For example, `n=26`: `1, 248, 6, 110, 25` → `1, 6, 25`.

Unfortunately, random generator is slow function. We lost resources and generates 5 numbers and used only 3 of them. Maybe we can use this bigger numbers (`110` and `248`)?

I found a solution with binary masks. The random generator generates not numbers, but bytes sequences. So `248` → `11111000`. We see how many binary numbers we need for `n` (`26` → `11010`). Technically we getting binary mask (`32`). Then we trim biggest binary numbers `11111000` → `11000`. `11000` is `24` and can be used as random number.

Of course, even after binary mask some numbers could be bigger than `n` (`11111` → `31`). In this case we still need to remove them.

**Comment by ai** [comment]
> var step = Math.ceil(1.6 * mask * size / alphabet.length)

Second hack. The slowest part of hardware random generator is initialization. An only first random byte is hardware randomness. Then, the browser uses a special algorithm to make infinite pseudo-random sequences from this first random byte.

So, the fastest way to use RNG is to call it only once. But because we need to remove random number bigger than `n`, we don’t know how many numbers we need.

So, we need to predict the numbers :).
1. Of course, we need at least `size` random numbers. `random(size)`
2. Then, for binary mask `32` and `n=17` we need more tries, then for `n=31` with same binary mask (because we will remove more random numbers). `random((mask / n) * size)`
3. Then, we need a little more numbers. Because generating some unnecessary numbers is faster than addition RNG initialization (the costs on mistakes are different). So `random(1.6 * (mask / n) * size)`

**Comment by akx** [comment]
Thanks for the explanation! :) So 1.6 is just an empirically figured multiplier, I guess?

> (it could not be used in nanoid since we use hardware random generator. And this RNG returns integers, not floats).

But you can divide the integer by the range of the data type, i.e. 255 in this case... though hmm, now that I think of it, I realize that the peaks from using `crypto.randomBytes(1)[0] / 255.` may stem (somehow ✨ ) from the fact that `Math.random()` would never return 1, whereas that division may:
> The `Math.random()` function returns a floating-point, pseudo-random number in the range [0, 1); that is, from 0 (inclusive) up to but not including 1 (exclusive), 

Using 24 bits of random data to generate a floating point number in the range [0, 1 / ((1 << 24) + 1)] (i.e. very close to [0, 1) especially [given this article](https://lemire.me/blog/2017/02/28/how-many-floating-point-numbers-are-in-the-interval-01/) ) seems to yield passable results:

```javascript
const cryptoRand3 = () => {
  const [a, b, c] = crypto.randomBytes(3);
  return ((a << 16) | (b << 8) | c) / ((1 << 24));
}
```

![image](https://user-images.githubusercontent.com/58669/30375563-aeb18d18-9891-11e7-82db-542d321f21ee.png)

**Comment by ai** [comment]
> So 1.6 is just an empirically figured multiplier

Yeap

> Using 24 bits of random data to generate a floating point number in the range

Crazy :D. But in this case we will need more random bits.

**Comment by hidehalo** [comment]
Hey guys @ai @akx , I am wondering how to generate that graph of benchmark report 😄

**Comment by akx** [comment]
@hidehalo I had the script generate a tab-separated list of characters and occurrence counts, then charted it with OSX's Numbers :)
