### ISSUE TITLE
Citation needed

### ISSUE THREAD

**Issue by jchook** [ai/nanoid#225]
> **Uniformity.** random % alphabet is a popular mistake to make when coding an ID generator. The distribution will not be even; there will be a lower chance for some symbols to appear compared to others. So, it will reduce the number of tries when brute-forcing. Nano ID uses a [better algorithm](https://github.com/ai/nanoid/blob/master/format.js) and is tested for uniformity

1. The link is broken
1. Your [even distribution](https://github.com/ai/nanoid/blob/1144d27f333b5299cb6a2776c487be9253fbee5a/index.js#L21) method seems to use a bitmask, which can only reduce the possible combinations.

Do you have any math to support your argument?

(e.g. using the default alphabet)

**Comment by ai** [comment]
> Citation needed

Here is a link, where I took this idea: https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba

![20200619230455](https://user-images.githubusercontent.com/19343/85189938-5bdda880-b281-11ea-9cb1-88e9f08aca56.png)

> 1. The link is broken

I fixed the link. Thanks.

> 2. Your even distribution method seems to use a bitmask, which can only reduce the possible combinations.

We need a way to convert a random number from 0…255 to 0…N (where n is alphabet size - 1).

We use 2 different algorithms: one for default and second for the custom alphabet.

We know the size of the default alphabet. Likely for us, the default alphabet has 64 symbols. So we need a way to convert random number between 0…255 to 0…63. Since 256 and 64 both `2^x` numbers, we can use a bitmask to remove unnecessary 2 random bits:

```js
randomByte & 63 // it is like applying 00111111 bitmask to random byte, to get only 6 random bits
```

For the custom alphabet, we can’t be sure about the alphabet size. We can’t bitmask, because alphabet size could be not a `2^x` number.

So we are applying another hack:

1. We [find](https://github.com/ai/nanoid/blob/master/index.js#L21-L25) the closest `2^x` number (if we have 13 symbols in the alphabet we will get 16).
2. We [generate](https://github.com/ai/nanoid/blob/master/index.js#L34-L38) a little more random bytes (if we need 6 symbols in ID, we will generate 8 random bytes).
3. We apply bitmask to random bytes to make them closer to alphabet size (in this example we convert 0…255 to 0…15).
4. Then we ignore bytes bigger than alphabet size (ignore random bytes bigger than 13).

> Do you have any math to support your argument?

Here is a unit test, that proofs that we have a flat distribution

https://github.com/ai/nanoid/blob/master/test/index.test.js#L47-L71

**Comment by ai** [comment]
Do you have other questions?

**Comment by jchook** [comment]
Awesome thank you very much for the explanation. 

It makes total sense to me now how it maintains an even distribution per character *per place*. Apologies for my knee-jerk post about this. Should have given it more investigation.

Excellent work with nanoid.
