### ISSUE TITLE
Cannot be used in browser any more?

### ISSUE THREAD

**Issue by etclub** [ai/nanoid#253]
See the issue at https://github.com/sveltejs/template/issues/200

**Comment by ai** [comment]
What builder do you use to prepare imports for ESM? Nano ID uses [`dual-publish`](https://github.com/ai/dual-publish/) which generates `index.dev.js` and `index.prod.js` and `exports.development` in `package.json` to avoid having `process.env.NODE_ENV` in the browser.

Seems like your builder do not support `production`/`development` in `package.exports`. You need to create an issue there.

**Comment by lukeed** [comment]
Those export keys/conditions are **only** supported by webpack. It's something they made up. https://webpack.js.org/guides/package-exports/#optimizations

You should add a  `browser` (string) condition in your `exports` map (I'd point this to production value). Every bundler/resolver is able to read that key (at least behind an option).

I assume that webpack will still prioritize `exports.browser.production` over `exports.browser` if both exist, but you'd have to ask them since they invented it.

```js
// Current (only works in webpack)
"exports": {
    ".": {
      "browser": {
        "development": "./index.dev.js",
        "production": "./index.prod.js"
      },
  // ...
}

// Suggested (*should* work in all)
// Confirm w/ webpack wrt priority
"exports": {
    ".": {
      "browser": [
        "./index.prod.js",
        {
          "development": "./index.dev.js",
          "production": "./index.prod.js"
        }
      ],
    // ...
}
```

**Comment by ai** [comment]
We have very useful checks and warnings in `if (process.env.NODE_ENV !== 'production')` blocks. Most of the builders support `process.env.NODE_ENV` hack (including `esbuild`, Rollup and Parcel). This is why I do not want to disable this warning by setting `"browser": ["./index.prod.js", {}]`.

Let’s find what builder or CDN was used by @etclub to suggest a better solution.

**Comment by lukeed** [comment]
Rollup does not replace by default. Can via `@rollup/plugin-replace`. 

My point is that the way you have `exports.browser` setup for the **main** entry will only work in webpack. No other bundler will know what to do with `{ development, production }` object, since those keys are meaningless & non-standard (except to webpack).

**Comment by ai** [comment]
@lukeed let’s create a separated issue in `dual-publish`

**Comment by lukeed** [comment]
It's the same issue. @etclub came from Svelte template, which is only configured for Rollup and webpack.

If it was new webpack, this would not be happening.

Old webpack would not even look at exports map. Ergo only Rollup is left, since template is not configured for anything else, and Rollup _does_ look at `exports| but (correctly) does not apply webpack's custom behavior.

You should transfer this issue to dual-publish probably

**Comment by ai** [comment]
For webpack we gave also `package.browser`. I 100% sure that `nanoid` works in webpack.

**Comment by lukeed** [comment]
Yes. I am not saying it doesn't.

I am saying that it **only** works in webpack (and Node).

**Comment by ai** [comment]
In `dual-publish` we have tests with Parcel, Rollup, and even esbuild. We also tested with jspm.

**Comment by lukeed** [comment]
You do not have a test for `exports.browser.development` and `exports.browser.production` -- which is what this issue is about. ONLY webpack can understand that object shape. Everything else expects a single string, or an object of relative file paths as keys.

https://github.com/ai/dual-publish/search?q=browser&type=

Unsubscribing from this thread, sorry, there's nothing else I can say to help explain this & I'm not sure if you're being defensive or not. 

Let me know if there's a specific thing I can address. Happy to help out but don't want to go around in circles :)

**Comment by etclub** [comment]
@ai 
I am using rollup. 
But I am not an export in rollup or webpack.
What I can tell is that nanoid stops working in browser.
You can reproduce it as I said at https://github.com/sveltejs/template/issues/200

**Comment by ai** [comment]
@etclub here is Rollup instructions: https://github.com/ai/nanoid#rollup
