### ISSUE TITLE
cant import v4.0.1 in TypeScript

### ISSUE THREAD

**Issue by kehiy** [ai/nanoid#418]
I'm trying to import nanoid in ts like this:
``` typescript
import { nanoid } from 'nanoid';
const id = nanoid();
console.log(id);
```

but I get this error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\projects\node_modules\nanoid\index.js from D:\projects\SIFER\SIFER-backend\src\controllers\uniqueCipherController.ts not supported.
Instead change the require of index.js in D:\projects\a.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by ai** [comment]
Nano ID 4.0 is ESM-only project. It works only with `import`. I recommend moving your project to ESM. Or you can install `npm install nanoid@3` instead.

https://github.com/ai/nanoid#install

**Comment by kehiy** [comment]
but I'm using import now!

**Comment by ai** [comment]
Are you using TypeScript? With wrong settings it will compile `import` to `require`.

**Comment by kehiy** [comment]
yes! 
I think my ts config is problem😐

**Comment by kasir-barati** [comment]
@ai it is not always an option to config like this: 

```ts
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "module": "ES6",
        "target": "es2017",
    }
}
```

At least not when you are using NestJS. Because then you cannot import `@nestjs/*`. What do you think? Should NestJS move away from commonjs too? Just asked out of curiosity.

# Solution for NestJS and those who cannot move away from commonjs but still wanted the latest version:

https://stackoverflow.com/a/73420399/8784518
e.x.
```ts
async function nanoidGenerator(length = 20) {
    const { customAlphabet } = await import('nanoid');
    return customAlphabet(PUBLIC_ID_SEED, length)();
}
```
