### ISSUE TITLE
[Question] Comparison with shortid

### ISSUE THREAD

**Issue by Justineo** [ai/nanoid#8]
@ai I noticed earlier you started to maintain [dylang/shortid](https://github.com/dylang/shortid) so I'm wondering that what's the difference between shortid and nanoid?

**Comment by ai** [comment]
@Justineo main differences:

1. `nanoid` is extremely smaller. This is why I create a new package, because it was very hard to keep size with `shortid` API.
2. `shortid` have some [problem with uniformity](https://github.com/dylang/shortid/issues/85). Because it is big problem, it is hard to find the reason.
3. `shortid` uses `-` in the alphabet and it has [some problem in the end of URL](https://github.com/dylang/shortid/issues/96). Nano ID could start from the beginning and replace `-` to safer `~`.
4. `shortid` have [no stateless API](https://github.com/dylang/shortid/issues/48).
5. There [is no API](https://github.com/dylang/shortid/issues/81) to specify ID length.

**Comment by ai** [comment]
Right now I plan to backport some features back to `shortid`, at least to fix uniformity problem.

**Comment by Justineo** [comment]
Thanks for the explanation. Great work!
